In [224]:
import numpy as np
import pandas as pd
from google.colab import files
from datetime import timedelta

In [283]:
def import_csv(service_name):
  try:
    num_of_sales = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/num_of_sales.csv'.format(service_name)).fillna(0)
  except:
    num_of_sales = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/number_of_sales.csv'.format(service_name)).fillna(0)
  average_usd = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/average_usd.csv'.format(service_name)).fillna(0)
  sales_usd = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/sales_usd.csv'.format(service_name)).fillna(0)
  active_market_wallets = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/active_market_wallets.csv'.format(service_name)).fillna(0)
  unique_buyers = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/{}/unique_buyers.csv'.format(service_name)).fillna(0)

  return[num_of_sales,average_usd,sales_usd,active_market_wallets,unique_buyers]

csvs1 = import_csv("art_blocks_art")
csvs2 = import_csv("axie_infinity_game")
csvs3 = import_csv("bored_ape_yacht_club_collection")
csvs4 = import_csv("creepz_game")
csvs5 = import_csv("crypto_punk_collection")
csvs6 = import_csv("decentraland_metaverse")
csvs7 = import_csv("the_sandbox_metaverse")
csvs8 = import_csv("superrare_art")

In [284]:
csvs2[1].head()

              DateTime  Average USD  Average USD.1
0  2018-02-15 00:00:00          0.0            0.0
1  2018-02-16 00:00:00          0.0            0.0
2  2018-02-17 00:00:00          0.0            0.0
3  2018-02-18 00:00:00          0.0            0.0
4  2018-02-19 00:00:00          0.0            0.0

In [285]:
# max_date_df = csvs[0]
# max_date_len = csvs[0].shape[0]
# for i in csvs:
#   if(i.shape[0] > max_date_len):
#     max_date_len = i.shape[0]
#     max_date_df = i

# # def fill_missing_dates(target_df, max_date_df):
# #   idx = pd.date_range(max_date_df['DateTime'].min(), max_date_df['DateTime'].max())
# #   new_target_df = target_df.reindex(idx)
# #   return new_target_df

def fill_missing_dates(target_df):
  # idx = pd.date_range(target_df['DateTime'].min(), target_df['DateTime'].max())
  try:
    target_df['DateTime'] = pd.to_datetime(target_df['DateTime'], format = '%Y-%m-%d %H:%M:%S')
    target_df.set_index("DateTime", inplace=True)
  except:
    pass
  target_df = target_df.resample('D').interpolate().reset_index()
  
  return target_df 
  
def integrate_into_one_csv(csvs):
  filled_csvs =[]
  for i in csvs:
    filled_csvs.append(fill_missing_dates(i))
  
  
  filled_csvs[0] = filled_csvs[0].drop(filled_csvs[0].columns[-1], axis=1)
  for i in range(len(filled_csvs) -1):
    col_name = filled_csvs[i+1].columns[1]
    filled_csvs[0].loc[:,col_name] = filled_csvs[i+1].loc[:,col_name]
  return filled_csvs[0]

integrated_df1 = integrate_into_one_csv(csvs1)
integrated_df2 = integrate_into_one_csv(csvs2)
integrated_df3 = integrate_into_one_csv(csvs3)
integrated_df4 = integrate_into_one_csv(csvs4)
integrated_df5 = integrate_into_one_csv(csvs5)
integrated_df6 = integrate_into_one_csv(csvs6)
integrated_df7 = integrate_into_one_csv(csvs7)
integrated_df8 = integrate_into_one_csv(csvs8)

In [286]:
# integrated_df1.head()
# integrated_df2.head()
# integrated_df3.head()
# integrated_df4.head()
# integrated_df5.head()
# integrated_df6.head()
integrated_df7.head()
# integrated_df8.head()

,DateTime,Number of sales,Average USD,Sales USD,Active market wallets,Unique buyers
0,2019-12-02,0.0,0.00,0.00,0.0,0.0
1,2019-12-03,0.0,0.00,0.00,0.0,0.0
2,2019-12-04,12.0,28.19,338.34,5.0,4.0
3,2019-12-05,2972.0,26.19,77827.27,170.0,168.0
4,2019-12-06,8.0,55.09,440.73,10.0,7.0

In [288]:
# integrated_df1.to_csv('integrated_df1.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df2.to_csv('integrated_df2.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df3.to_csv('integrated_df3.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df4.to_csv('integrated_df4.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df5.to_csv('integrated_df5.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df6.to_csv('integrated_df6.csv', encoding = 'utf-8-sig', index=False) 
integrated_df7.to_csv('integrated_df7.csv', encoding = 'utf-8-sig', index=False) 
# integrated_df8.to_csv('integrated_df8.csv', encoding = 'utf-8-sig', index=False) 
# files.download('integrated_df1.csv')
# files.download('integrated_df2.csv')
# files.download('integrated_df3.csv')
# files.download('integrated_df4.csv')
# files.download('integrated_df5.csv')
# files.download('integrated_df6.csv')
files.download('integrated_df7.csv')
# files.download('integrated_df8.csv')

In [263]:
csv_NASDAQ = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/NASDAQ.csv').fillna(0)
try:
    csv_NASDAQ['date'] = pd.to_datetime(csv_NASDAQ['date'], format = '%Y년 %m월 %d일')
    csv_NASDAQ.set_index("date", inplace=True)
except:
  pass
csv_NASDAQ = csv_NASDAQ.sort_values(by=['date'], ascending=True)
# print(csv_NASDAQ.dtypes)

csv_NASDAQ = csv_NASDAQ.resample('D').ffill()
# csv_NASDAQ.head()

#2017/1/1 과 2일이 빠진것을 보충.
prev_two_rows = csv_NASDAQ.iloc[0:2,:].copy()
prev_two_rows.iloc[1,:] = csv_NASDAQ.iloc[0,:]

concat_csv = pd.concat([prev_two_rows, csv_NASDAQ])
old_index = (concat_csv.index).tolist()
old_index[0] = pd.to_datetime(old_index[2]) - pd.Timedelta(days=2)
old_index[1] = pd.to_datetime(old_index[2]) - pd.Timedelta(days=1)
concat_csv.index = old_index
# concat_csv.head()

# 2022/05/14, 15를 보충.
last_two_rows = concat_csv.iloc[-2:,:].copy()
last_two_rows.iloc[0,:] = concat_csv.iloc[-1,:]

concat_csv = pd.concat([ concat_csv, last_two_rows])
old_index = (concat_csv.index).tolist()
old_index[-2] = pd.to_datetime(old_index[-3]) + pd.Timedelta(days=1)
old_index[-1] = pd.to_datetime(old_index[-3]) + pd.Timedelta(days=2)
concat_csv.index = old_index
# concat_csv.head(1961)

,close,open,high,low,volume,change_percentage
2017-01-01,"5,429.08","5,425.62","5,452.56","5,397.99",450.68M,0.85%
2017-01-02,"5,429.08","5,425.62","5,452.56","5,397.99",450.68M,0.85%
2017-01-03,"5,429.08","5,425.62","5,452.56","5,397.99",450.68M,0.85%
2017-01-04,"5,477.01","5,440.91","5,482.35","5,440.24",455.34M,0.88%
2017-01-05,"5,487.94","5,474.39","5,495.85","5,464.36",423.64M,0.20%
...,...,...,...,...,...,...
2022-05-11,"11,364.24","11,645.57","11,844.50","11,339.18",1.27B,-3.18%
2022-05-12,"11,370.96","11,199.25","11,547.33","11,108.76",1.40B,0.06%
2022-05-13,"11,805.00","11,555.97","11,856.71","11,510.25",1.23B,3.82%
2022-05-14,"11,805.00","11,555.97","11,856.71","11,510.25",1.23B,3.82%
2022-05-15,"11,805.00","11,555.97","11,856.71","11,510.25",1.23B,3.82%

In [264]:
concat_csv.to_csv('concat_csv.csv', encoding = 'utf-8-sig') 
files.download('concat_csv.csv')

In [269]:
csv_eth = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/ETH_price.csv').fillna(0)
def fill_missing_dates(target_df):
  target_df['date'] = pd.to_datetime(target_df['date'], format = '%Y-%m-%d')[:9]
  target_df.set_index("date", inplace=True)
  target_df = target_df.drop
  return target_df

filled_csv_eth = fill_missing_dates(csv_eth)
filled_csv_eth.head()

1961
1961 days 00:04:00

                     weighted  close   high   low   open      volume
date
2017-01-01 09:01:00      8.30   8.18   8.60  8.08   8.13   494058.62
2017-01-02 09:01:00      8.27   8.36   8.53  8.05   8.18   576281.05
2017-01-03 09:01:00      9.27   9.69  10.02  8.24   8.36  1727093.22
2017-01-04 09:01:00     10.50  10.98  10.99  9.34   9.69  2520314.73
2017-01-05 09:01:00     10.66  10.28  11.80  9.08  10.98  3301868.66

In [279]:
csv_usd_index = pd.read_csv('https://raw.githubusercontent.com/qwqw3535/CS370_Machine_Learning/main/original_data_daily/csv_usd_index.csv').fillna(0)

try:
    csv_usd_index['date'] = pd.to_datetime(csv_usd_index['date'], format = '%Y년 %m월 %d일')
    csv_usd_index.set_index("date", inplace=True)
except:
  pass
csv_usd_index = csv_usd_index.sort_values(by=['date'], ascending=True)
# print(csv_NASDAQ.dtypes)

# 2017 01 01 을 추가, 2022 05 16을 제거
csv_usd_index = csv_usd_index.resample('D').ffill()
csv_usd_index= csv_usd_index.shift(periods=1)
csv_usd_index.iloc[0,:] =csv_usd_index.iloc[1,:]

old_index = csv_usd_index.index.tolist()
old_index.pop()

old_index.insert(0, pd.to_datetime(old_index[0]) - pd.Timedelta(days=1))
csv_usd_index.index = old_index
csv_usd_index.head(2000)

             close    open    high     low change_percentage
2017-01-01  102.83  102.38  102.94  102.21             0.61%
2017-01-02  102.83  102.38  102.94  102.21             0.61%
2017-01-03  103.21  102.88  103.82  102.59             0.37%
2017-01-04  102.70  103.17  103.44  102.39            -0.49%
2017-01-05  101.52  102.45  102.51  101.30            -1.15%
...            ...     ...     ...     ...               ...
2022-05-11  103.85  103.90  104.11  103.37            -0.07%
2022-05-12  104.85  104.01  104.93  103.88             0.97%
2022-05-13  104.56  104.77  105.00  104.46            -0.27%
2022-05-14  104.56  104.77  105.00  104.46            -0.27%
2022-05-15  104.57  104.46  104.59  104.46             0.00%

[1961 rows x 5 columns]

In [280]:
csv_usd_index.to_csv('csv_usd_index.csv', encoding = 'utf-8-sig') 
files.download('csv_usd_index.csv')